In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
import joblib
import os

In [10]:
from google.colab import files

uploaded = files.upload()

Saving education_career_success.csv to education_career_success (1).csv

In [11]:
import os

print(os.listdir())

['.config', 'education_career_success.csv', 'education_career_success (1).csv', 'sample_data']

In [12]:
import pandas as pd

df = pd.read_csv("education_career_success.csv")

df.head()

,Student_ID,Age,Gender,High_School_GPA,SAT_Score,University_GPA,Field_of_Study,Internships_Completed,Projects_Completed,Certifications,Soft_Skills_Score,Networking_Score,Job_Offers,Starting_Salary,Career_Satisfaction,Years_to_Promotion,Current_Job_Level,Work_Life_Balance,Entrepreneurship
0,S001,22,Male,3.8,1450,3.6,Computer Science,3,7,2,8,7,3,85000,8,2,Mid,7,No
1,S002,24,Female,3.6,1380,3.4,Business,2,5,3,7,6,2,65000,7,3,Mid,6,No
2,S003,21,Male,3.9,1520,3.8,Engineering,4,9,4,9,8,4,120000,9,1,Senior,6,No
3,S004,23,Female,3.5,1300,3.2,Psychology,1,3,1,6,5,1,48000,6,4,Entry,8,No
4,S005,25,Male,3.7,1420,3.5,Medicine,2,6,2,8,7,3,95000,8,2,Mid,5,No

In [13]:
# Fill missing values safely
for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipykernel_1308/3550143829.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_1308/3550143829.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [14]:
categorical_cols = [
    "Gender",
    "Field_of_Study",
    "Current_Job_Level",
    "Entrepreneurship"
]

In [15]:
encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

print("Encoding Completed")

Encoding Completed

In [16]:
features = [
    "Age",
    "High_School_GPA",
    "SAT_Score",
    "University_GPA",
    "Internships_Completed",
    "Projects_Completed",
    "Certifications",
    "Soft_Skills_Score",
    "Networking_Score",
    "Job_Offers",
    "Starting_Salary",
    "Career_Satisfaction",
    "Years_to_Promotion",
    "Work_Life_Balance",
    "Gender",
    "Field_of_Study",
    "Current_Job_Level",
    "Entrepreneurship"
]

df_model = df[features]

In [17]:
print("Dataset ready for training")
df_model.head()

Dataset ready for training

,Age,High_School_GPA,SAT_Score,University_GPA,Internships_Completed,Projects_Completed,Certifications,Soft_Skills_Score,Networking_Score,Job_Offers,Starting_Salary,Career_Satisfaction,Years_to_Promotion,Work_Life_Balance,Gender,Field_of_Study,Current_Job_Level,Entrepreneurship
0,22,3.8,1450,3.6,3,7,2,8,7,3,85000,8,2,7,1,2,1,0
1,24,3.6,1380,3.4,2,5,3,7,6,2,65000,7,3,6,0,1,1,0
2,21,3.9,1520,3.8,4,9,4,9,8,4,120000,9,1,6,1,4,2,0
3,23,3.5,1300,3.2,1,3,1,6,5,1,48000,6,4,8,0,10,0,0
4,25,3.7,1420,3.5,2,6,2,8,7,3,95000,8,2,5,1,8,1,0

In [18]:
os.makedirs("models", exist_ok=True)

In [19]:
joblib.dump(encoders, "models/feature_encoders.pkl")

print("Encoders saved successfully")

Encoders saved successfully

In [20]:
joblib.dump(features, "models/feature_list.pkl")

print("Feature list saved successfully")

Feature list saved successfully

In [24]:
from google.colab import files

files.download("models/feature_list.pkl")

In [23]:
import os

print(os.listdir("models"))

['feature_encoders.pkl', 'feature_list.pkl']

In [25]:
import os

os.makedirs("models", exist_ok=True)

In [26]:
from google.colab import files
files.download("models/feature_list.pkl")